name:                Spock-api
version:             0.16.0.0
synopsis:            Another Haskell web framework for rapid development
description:         API definition DSL for Spock web framework
Homepage:            https://www.spock.li
Bug-reports:         https://github.com/agrafix/Spock/issues
license:             BSD3
license-file:        LICENSE
author:              Alexander Thiemann <mail@athiemann.net>
maintainer:          Alexander Thiemann <mail@athiemann.net>
copyright:           (c) 2013 - 2021 Alexander Thiemann
category:            Web
build-type:          Simple
cabal-version:       2.0
tested-with:         GHC==9.14.1
extra-source-files:  README.md

library
  hs-source-dirs:      src
  exposed-modules:     Web.Spock.Api, Web.Spock.Api.Document
  build-depends:
                aeson >= 2.0,
                base >= 4.12 && < 5,
                bytestring,
                containers,
                http-api-data >= 0.2,
                http-types,
                text,
                reroute >= 0.9.0.0,
                hvect >= 0.3.1,
                deepseq
  ghc-options: -Wall
  default-language:    Haskell2010

test-suite api-document-tests
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  build-depends: base, aeson, hspec, Spock-api, text, vector
  default-language: Haskell2010
  ghc-options: -Wall

source-repository head
  type:     git
  location: https://github.com/agrafix/Spock
