# Site settings
title: Spock Web Framework
email: mail@athiemann.net
description: > # this means to ignore newlines until "baseurl:"
  Spock is a lightweight Haskell web framework inspired by Ruby's Sinatra. It provides a full
  toolbox including everything to get a quick start into web programming using Haskell.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.spock.li" # the base hostname & protocol for your site
twitter_username: agrafix
github_username:  agrafix

# Build settings
markdown: kramdown