# Use a fixed package set with the latest stable compiler.
resolver: nightly-2026-09-01
compiler: ghc-9.14.1

packages:
  - Spock/
  - Spock-api/
  - Spock-api-server/
  - Spock-core/
  - reroute/
  - examples/rendering/
