flags: {}
packages:
- Spock/
- Spock-api/
- Spock-api-server/
- Spock-core/
- reroute/
extra-deps:
- primitive-extras-0.8
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.4
- resourcet-1.2.4
- deferred-folds-0.9.10.1
- focus-1.0.1.3
- primitive-0.7.0.1
resolver: lts-15.3
