resolver: lts-19.16

packages:
  - Spock/
  - Spock-api/
  - Spock-api-server/
  - Spock-core/
  - reroute/
extra-deps:
  - stm-containers-1.2
  - stm-hamt-1.2.0.7
  - primitive-extras-0.10.1.5
  - primitive-unlifted-0.1.3.1
  - focus-1.0.3
  - superbuffer-0.3.1.2

  - regex-posix-clib-2.7

flags:
  regex-posix:
    _regex-posix-clib: true
