#!/usr/bin/env python3
"""Install the pinned JavaScript cross compiler and Emscripten into an isolated prefix."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shlex
import shutil
import subprocess
import tempfile
import urllib.request

CONFIG = json.loads(Path(__file__).with_name("javascript-toolchain.json").read_text())


def run(args, **kwargs):
    return subprocess.run([str(a) for a in args], check=True, **kwargs)


def output(args, **kwargs):
    return run(args, text=True, stdout=subprocess.PIPE, **kwargs).stdout.strip()


def setup(prefix):
    archive_name, checksum = CONFIG["archives"][f"{platform.system()}-{platform.machine()}"]
    for command in ["git", "make", "tar", "xz", "node"]:
        if not shutil.which(command):
            raise SystemExit(f"Install {command} first (use Node 22).")
    prefix = prefix.expanduser().resolve()
    prefix.mkdir(parents=True, exist_ok=True)
    emsdk = prefix / "emsdk"
    compiler = prefix / f'javascript-{CONFIG["ghc"]}'
    if not emsdk.exists():
        run(["git", "clone", "--depth=1", "--branch", CONFIG["emscripten"],
             "https://github.com/emscripten-core/emsdk.git", emsdk])
    if output(["git", "rev-parse", "HEAD"], cwd=emsdk) != CONFIG["emsdk_commit"]:
        raise SystemExit(f"{emsdk} has a different revision; choose a fresh --prefix.")
    run([emsdk / "emsdk", "install", CONFIG["emscripten"]], cwd=emsdk)
    run([emsdk / "emsdk", "activate", CONFIG["emscripten"]], cwd=emsdk)
    env = os.environ.copy()
    env.update(EMSDK=str(emsdk), EM_CONFIG=str(emsdk / ".emscripten"))
    env["PATH"] = os.pathsep.join([str(compiler / "bin"), str(emsdk),
                                  str(emsdk / "upstream/emscripten"), env["PATH"]])
    ghc = compiler / "bin/javascript-unknown-ghcjs-ghc"
    if ghc.exists():
        if output([ghc, "--numeric-version"], env=env) != CONFIG["ghc"]:
            raise SystemExit(f"{compiler} contains another compiler; choose a fresh --prefix.")
    else:
        # Verify the GHCup-published hash before extracting or executing anything.
        with tempfile.TemporaryDirectory(prefix="download-", dir=prefix) as directory:
            archive = Path(directory) / archive_name
            with urllib.request.urlopen(CONFIG["base_url"] + archive_name) as response, archive.open("wb") as target:
                shutil.copyfileobj(response, target)
            with archive.open("rb") as source:
                digest = hashlib.file_digest(source, "sha256").hexdigest()
            if digest != checksum:
                raise SystemExit("GHC archive checksum mismatch.")
            run(["tar", "-xf", archive, "-C", directory])
            source = Path(directory) / f'ghc-{CONFIG["ghc"]}-javascript-unknown-ghcjs'
            run(["emconfigure", "./configure", f"--prefix={compiler}"], cwd=source, env=env)
            run(["make", "install"], cwd=source, env=env)
    activation = prefix / "env.sh"
    activation.write_text(
        "# Generated by Spock's scripts/setup-javascript.py; source this file.\n"
        f"export EMSDK={shlex.quote(str(emsdk))}\n"
        f"export EM_CONFIG={shlex.quote(str(emsdk / '.emscripten'))}\n"
        f"export PATH={shlex.quote(os.pathsep.join([str(compiler / 'bin'), str(emsdk), str(emsdk / 'upstream/emscripten')]))}:\"$PATH\"\n")
    run([ghc, "--version"], env=env)
    run(["emcc", "--version"], env=env)
    print(f"Ready. Run: source {shlex.quote(str(activation))}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", type=Path, required=True)
    setup(parser.parse_args().prefix)
