source "https://rubygems.org"

# Match the Jekyll version used by GitHub Pages.
gem "jekyll", "3.10.0"
gem "jekyll-redirect-from", "~> 0.16"
gem "kramdown-parser-gfm", "~> 1.1"
gem "csv"
gem "logger"
gem "base64"
gem "bigdecimal"
